owner: MaxAtslega
repo: status

sites:
  - name: GitLab
    url: https://git.atslega.network
  - name: Mailcow
    url: https://mail.atslega.network
  - name: Gameserver Panel
    url: https://gpanel.atslega.network
  - name: Nextcloud
    url: https://cloud.atslega.network
  - name: Bitwarden
    url: https://pw.atslega.network
  - name: Wiki
    url: https://wiki.atslega.network
  - name: Spotify Status
    url: https://spotify-live.atslega.de/api/spotify
  - name: Librenms
    url: https://librenms.atslega.network
    
status-website:
  cname: status.atslega.network
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AN Status
  introTitle: "**AtslegaNetwork Status**"
  introMessage: ""
  theme: night
  navbar:
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
